[[main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 40

[[main]]
    name = 'Courses'
    pageRef = '/courses'
    weight = 30

[[main]]
    name = 'Services'
    pageRef = '/services'
    weight = 20

[[social]]
    name = "GitHub"
    url = "https://github.com/nheirbaut"
    weight = 1
    [social.Params]
        icon = "bi bi-github"

[[social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/nielsheirbaut"
    weight = 2
    [social.Params]
        icon = "bi bi-linkedin"
