[[main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 30

[[main]]
    name = 'Training'
    pageRef = '/courses'
    weight = 40

[[main]]
    name = 'Services'
    pageRef = '/services'
    weight = 50
