baseURL = "http://opilo.nl/"
languageCode = "nl-nl"
title = "Opilo Automatisering"
theme = "opilo-theme"

# [menu]

#   [[menu.main]]
#     name = "Over mij"
#     identifier = "about"
#     url = "/about"

#   [[menu.main]]
#     name = "Diensten"
#     identifier = "services"

